{% set name = "pytest-localstack" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91be109a98f3737e10b0b1de8f0cf48f30abee878a77099862fad2bed6de689c

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - botocore >=1.4.31,!=1.4.45
    - contextlib2
    - docker-py
    - mock
    - pluggy >=0.6.0
    - pytest >=3.3.0
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_localstack
    - pytest_localstack.contrib

about:
  home: https://github.com/mintel/pytest-localstack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Pytest plugin for AWS integration tests"
  doc_url: "https://pypi.org/project/pytest-localstack/"
  dev_url: "https://github.com/mintel/pytest-localstack"

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
